# Generated by Django 4.2.9 on 2026-02-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(blank=True, choices=[('helpdesk', 'Helpdesk'), ('equipment', 'Equipment'), ('device', 'Device')], max_length=100, null=True),
        ),
    ]
