# Generated by Django 4.2.9 on 2026-02-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
