# Generated by Django 4.2.9 on 2026-01-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userloginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginsession',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
