# Generated by Django 4.2.9 on 2026-01-23 16:14

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Django App', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=base.models.favicon_upload_to)),
                ('app_icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
